### ISSUE TITLE
[EPIC] Reduce bundle size

### ISSUE THREAD

**Issue by tumido** [tumido/malenovska-react#8]
Reduce footprint
- [] Reduce lodash size
- [] Extract assets if possible
- [] Switch to `preact`
- [] Move leaflet to correct chunk
- [] Remove immutable if possible
